development:
  adapter: postgresql
  encoding: unicode
  database: ivotd_development
  pool: 5
  username: adrianbrucecunanan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ivotd_test
  pool: 5
  username: adrianbrucecunanan
  password: